In [1]:
#!pip install numpy

In [2]:
#! pip install pandas

In [3]:
import numpy as np

In [4]:
l=[1,2,3,4]
print(l*3)
l=[1,'ABC',True]
print(type(l))

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]
<class 'list'>


In [5]:
b=np.array([1,2,3,4,5,6])
a=np.array([1,2,3,4])
print(a.dtype)
print(a)
print(a*3)
print(a)
print(a+10)

int32
[1 2 3 4]
[ 3  6  9 12]
[1 2 3 4]
[11 12 13 14]


In [6]:
print(l)
l=np.array(l)
l

[1, 'ABC', True]


array(['1', 'ABC', 'True'], dtype='<U11')

In [7]:
#l*3

In [8]:
a=np.array([1,2,3,4,5,6,7])
print(a)
print(a.shape)
print(a.ndim)

[1 2 3 4 5 6 7]
(7,)
1


In [9]:
a_2=np.array([[1,2],[3,4],[5,6]])
print(a_2)
print(a_2.shape)
print(a_2.ndim)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
2


In [10]:
a_z=np.zeros((3,4))
print(a_z)
print(a_z.shape)
print(a_z.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(3, 4)
2


In [11]:
a_n=np.random.random((3,4))
print(a_n)
print(a_n.shape)
print(a_n.ndim)

[[0.61671514 0.64007677 0.45059855 0.38535281]
 [0.93865668 0.4104056  0.02792607 0.28338337]
 [0.84813748 0.69151306 0.51601787 0.24265513]]
(3, 4)
2


In [12]:
a_l=np.linspace(0,100,10) # (start,stop,step)
print(a_l)
print(a_l.shape)
print(a_l.ndim)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
(10,)
1


In [13]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.size)
print(a.T)# the transpose will turn row into column and column into rows

(2, 3)
6
[[1 4]
 [2 5]
 [3 6]]


In [14]:
print(a)
print(a.shape)
b=a.reshape(3,2)
print("\n\n",b)
print(b.shape)
c=a.reshape(6,1)
print("\n\n",c)
print(c.shape)
d=a.reshape(1,6)
print("\n\n",d)
print(d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


 [[1 2]
 [3 4]
 [5 6]]
(3, 2)


 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


 [[1 2 3 4 5 6]]
(1, 6)


In [15]:
a=np.array([1,2,3,4,5,6]).reshape(2,3)
print(a)
b=np.array([7,8,9,10,11,12]).reshape(2,3)
print(b)
c=np.concatenate((a,b),axis=0)
print(c)
print(c.shape)
print(c.ndim)
d=np.concatenate((a,b),axis=1)
print(d)
print(d.shape)
print(d.ndim)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
(2, 6)
2


In [16]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [17]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
f=np.array([[1,2,3],[4,5,6]],dtype='float')
print(f)

[[1. 2. 3.]
 [4. 5. 6.]]


In [19]:
t=np.array((1,2,3))
t

array([1, 2, 3])

In [20]:
t=np.append(t,[4,5,6,7,8])

In [21]:
t

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
t=np.insert(t,2,[10,11,12,13])
t


array([ 1,  2, 10, 11, 12, 13,  3,  4,  5,  6,  7,  8])

In [23]:
t=np.delete(t,[2,3,4,5])
t

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [25]:
a=np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [26]:
a[-1]

9

In [27]:
a[2:4]

array([5, 7])

In [28]:
a=np.arange(20,30).reshape(5,2)
a

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [29]:
a[2,1]

25

In [30]:
f=a.flatten()
print(f.shape)
print(f)


(10,)
[20 21 22 23 24 25 26 27 28 29]


In [31]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
a[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
a[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [35]:
a=np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a=a+10
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
a/2

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [38]:
10>14

False

In [39]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
cond=a>15
a[cond]

array([16, 17, 18, 19, 20])

In [41]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
a>15

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [43]:
names=np.array(["Harry","Tom","Bob","Harry","Harry"])
names

array(['Harry', 'Tom', 'Bob', 'Harry', 'Harry'], dtype='<U5')

In [44]:
c=names=="Harry"
names[c]

array(['Harry', 'Harry', 'Harry'], dtype='<U5')

In [45]:
c=names!='Harry'
names[c]

array(['Tom', 'Bob'], dtype='<U5')

In [46]:
names=np.array(["Harry","Tom","Bob","Harry","Harry","Jerry","John","Abhishek","RohAN","Amit","Satvika Madam"])
names

array(['Harry', 'Tom', 'Bob', 'Harry', 'Harry', 'Jerry', 'John',
       'Abhishek', 'RohAN', 'Amit', 'Satvika Madam'], dtype='<U13')

In [47]:
cond1=names!='Tom'
cond2=names!='Jerry'
names[cond1&cond2]

array(['Harry', 'Bob', 'Harry', 'Harry', 'John', 'Abhishek', 'RohAN',
       'Amit', 'Satvika Madam'], dtype='<U13')

In [48]:
names[(names!='Tom')&(names!='Jerry')]

array(['Harry', 'Bob', 'Harry', 'Harry', 'John', 'Abhishek', 'RohAN',
       'Amit', 'Satvika Madam'], dtype='<U13')

In [49]:
names[(names!='Tom')&(names!='Jerry')]='Rahul'

In [50]:
names

array(['Rahul', 'Tom', 'Rahul', 'Rahul', 'Rahul', 'Jerry', 'Rahul',
       'Rahul', 'Rahul', 'Rahul', 'Rahul'], dtype='<U13')

In [51]:
a=np.array([[1,2,3],[4,5,6]])
print(np.mean(a))
print(np.std(a))
print(np.var(a))
print(np.sum(a))
print(np.prod(a))  #factorial 6*5*4*3*2*1

3.5
1.707825127659933
2.9166666666666665
21
720


In [52]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.max())
print("Max elements row-wise : ",arr.max(axis=1))
print(arr.sum())
print(arr.cumsum())

9
Max elements row-wise :  [3 6 9]
45
[ 1  3  6 10 15 21 28 36 45]


In [53]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print(a+b)
print(a.dot(b))
print(a*b)

[[2 4]
 [6 8]]
[[ 7 10]
 [15 22]]
[[ 1  4]
 [ 9 16]]
